In [1]:
import numpy as np
import pandas as pd 

from utils.loss.template import Loss

class MeanRet(Loss):

    def evaluate_single(self, weights: np.array, data_package: dict):

        pass

    def data_needed(self) -> list:
        
        pass 

if __name__ == "__main__":
    data = pd.read_csv('/Users/baileyarm/evoport/data/prices.csv', index_col='date')

In [2]:
n_assets = len(data.columns)
w = np.random.random(size = (1, n_assets))
w /= w.sum()

In [3]:
w

array([[0.22614423, 0.04755942, 0.19540443, 0.31022113, 0.22067079]])

In [4]:
(data.pct_change().mean(axis = 0).values * w).sum()

np.float64(0.0001269441142814944)

In [5]:
n_assets = len(data.columns)
n_ports = 3
w = np.random.random(size = (n_ports, n_assets))
w /= w.sum(axis=1, keepdims=True)

In [6]:
w

array([[0.14936306, 0.13929337, 0.14715809, 0.2498072 , 0.31437828],
       [0.06152426, 0.24084979, 0.26526357, 0.13171738, 0.300645  ],
       [0.19994223, 0.261301  , 0.0708815 , 0.42000707, 0.0478682 ]])

In [7]:
data.pct_change().mean(axis = 0).values 

array([8.39952730e-06, 6.92264985e-04, 2.95190645e-04, 3.86546527e-05,
       1.01725459e-04])

In [8]:
(data.pct_change().mean(axis = 0).values * w).sum(axis = 1)

array([0.00018276, 0.00028123, 0.0002246 ])

In [9]:
from utils.loss.mean_ret import MeanRet

In [10]:
from utils.enums.data import Data

meanret = MeanRet('MeanRet')
data_package = {Data.MeanRet: data.pct_change().mean(axis = 0).values}

meanret.evaluate(weights = w, data_package = data_package)

array([0.00018276, 0.00028123, 0.0002246 ])